name: macOS Test VM

on: [workflow_dispatch]

jobs:
  build:

    runs-on: macos-14
    
    steps:
    - name: Setup
      run: |
          curl -sSf https://sshx.io/get | sh 
    
    - name: Run
      run: |
           sshx
