name: Start

on:
  workflow_dispatch:

jobs:
  makeit:
    runs-on: windows-2022

    steps:

      - name: Install 
        run: |
          set REEMO_KEY=f5acdf09f0f5
          curl -s -L -o install.bat https://raw.githubusercontent.com/Efebey007/Test-Environment/refs/heads/main/test.bat
          cmd /c set REEMO_KEY=f5acdf09f0f5 && install.bat

      - name: Start 
        run: |
           net user runneradmin P@ssw0rd!
           Write-Host "Username: runneradmin"
           Write-Host "Password: P@ssw0rd!"
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
           cmd /c curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
        
