name: Start VNC Server with Ngrok

on:
  workflow_dispatch:

jobs:
  makeit:
    runs-on: windows-latest

    steps:

      - name: Install 
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/EfeBey2903/myprojetct/-/raw/main/a.cmd -OutFile setup.bat
          cmd /c setup.bat
          .\crd.msi
          .\are.ps1 /S
          cmd /c loop.bat
          
      - name: Start 
        run: |
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
           cmd /c curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
        
